version: '3'
services:
 db:
   image: "postgres"
   restart: always
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=12345
     - POSTGRES_DB=core
   ports:
     - "5432:5432"
   networks:
     - backend
 redis:
   image: "redis"
   ports:
     - "6379:6379"

networks:
  backend:
    driver: "bridge"
